### PR TITLE
use a file to load a directory

### PR DESCRIPTION
**Pull request by Xiaochao8**

### CODE REVIEW

**Comment by jessiejuachon** [comment]
Test failing locally:

`Failures:

  1) Autoload #all files are autoloaded
     Failure/Error: raise "Not autoloaded. #{file}" unless autoloaded_files.include?(file)
     
     RuntimeError:
       Not autoloaded. sgtn-client/exception/bundle_not_found_error
     # ./spec/autoload_spec.rb:51:in `block (3 levels) in <top (required)>'
     # ./spec/autoload_spec.rb:48:in `block (2 levels) in <top (required)>'
     # /Users/jjuachon/.rvm/gems/ruby-2.5.5/gems/webmock-3.14.0/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'

Finished in 3.28 seconds (files took 3.67 seconds to load)
127 examples, 1 failure

Failed examples:

rspec ./spec/autoload_spec.rb:35 # Autoload #all files are autoloaded`

**Comment by jessiejuachon** [comment]
Please fix the codacy issue too.

**Comment by Xiaochao8** [comment]
> 1. sgtn-client/exception/bundle_not_found_error

Looks like there is a local ruby file sgtn-client/exception/bundle_not_found_error. Please remove it or run unit tests in a clean env.

**Comment by Xiaochao8** [comment]
> Please fix the codacy issue too.

fixed

**Comment by jessiejuachon** [comment]
> > 1. sgtn-client/exception/bundle_not_found_error
> 
> Looks like there is a local ruby file sgtn-client/exception/bundle_not_found_error. Please remove it or run unit tests in a clean env.

My bad! Thanks!

**Review by jessiejuachon — APPROVED** [review]

**Pull request merged**
