### PR TITLE
Update GitHub Actions to fix incorrect unit test coverage issue

### PR DESCRIPTION
**Pull request by junw-33455432**

### CODE REVIEW

**Review by Xiaochao8 — COMMENTED** [review]
I didn't see the result.

**Comment by junw-33455432** [comment]
@Xiaochao8 It seems we still need to fix the unit test failure then we can go to the coverage stage to see the coverage information.

**Comment by Xiaochao8** [comment]
> @Xiaochao8 It seems we still need to fix the unit test failure then we can go to the coverage stage to see the coverage information.

The issue has been fixed. Please merge latest change from main branch,

**Comment by junw-33455432** [comment]
Close this PR and create a new PR to update codecov configure information

**Pull request closed without merging**
